local dap = require('dap')
vim.keymap.set('n', '<leader>b', dap.toggle_breakpoint)
vim.keymap.set('n', '<leader>c', dap.continue)
vim.keymap.set('n', '<leader>i', dap.step_into)
vim.keymap.set('n', '<leader>o', dap.step_out)
vim.keymap.set('n', '<leader>n', dap.step_over)
vim.keymap.set('n', '<leader>ds', function()
  local widgets = require('dap.ui.widgets')
  local scopes_sidebar = widgets.sidebar(widgets.scopes)
  scopes_sidebar.open()
end)
