local dap = require('dap')
local dapui = require('dapui')
vim.keymap.set('n', '<leader>b', dap.toggle_breakpoint)
vim.keymap.set('n', '<leader>r', dap.continue)
vim.keymap.set('n', '<leader>c', dap.continue)
vim.keymap.set('n', '<leader>i', dap.step_into)
vim.keymap.set('n', '<leader>o', dap.step_out)
vim.keymap.set('n', '<leader>n', dap.step_over)
vim.keymap.set('n', '<leader>x', dap.disconnect)
vim.keymap.set('n', '<leader>X', '<Cmd>lua require("dap").disconnect()<CR><Cmd>lua require("dapui").close()<CR>')
-- vim.keymap.set('n', '<leader>X', function()
--   require('dap').disconnect()
--   require('dapui').close()
-- end)
